apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }} 
  template: 
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers: 
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
